bmat/urls.py
""" Root URL config """

from django.conf.urls import include
from django.urls import path, re_path
from django.contrib import admin

import bmat.views, bookmarks.urls, users.urls, tags.urls, search.urls, autotags.urls

admin.autodiscover()

urlpatterns = [
    re_path(r'^$', bmat.views.home, name="home"),
    re_path(r'^privacy$', bmat.views.privacy, name="privacy"),
    path(r"admin/", admin.site.urls),
    
    re_path(r'^user/', include("users.urls")),
    re_path(r'^bookmarks/', include("bookmarks.urls")),
    re_path(r'^autotags/', include("autotags.urls")),
    re_path(r'^tags/', include("tags.urls")),
    re_path(r'^search/', include("search.urls")),
]

bookmarks/urls.py
""" URLs for bookmark related things 

URLs are:
- home
- export (For exporting bookmarks to HTML that browsers can import)
- add
- delete
- (bookmark)/html
- (bookmark)/rename

"""

from django.urls import re_path

import bookmarks.views as views

app_name="bookmarks"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^export$', views.export, name="export"),
    re_path(r'^add$', views.add, name="add"),
    re_path(r'^delete$', views.delete, name="delete"),
    re_path(r'^create$', views.create, name="create"),
    
    re_path(r'^(?P<bookmark>[0-9]+)/html$', views.html, name="html"),
    re_path(r'^(?P<bookmark>[0-9]+)/rename$', views.rename, name="rename"),
]

search/urls.py
""" URLs for searching

URLs are:
- home
- results (for the AJAX stuff)

"""

from django.urls import re_path
import search.views as views

app_name="search"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^results$', views.results, name="results"),
]

tags/urls.py
""" URLs for tag related things 

URLs are:
- home
- suggest/(query)
- delete
- rename/(tag)
- htmlBlock/(tag)
- tag
- untag
- ~(tag) (named "filter")

"""

from django.urls import re_path
import tags.views as views

app_name="tags"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    
    re_path(r'^suggest/(?P<value>.*)$', views.suggest, name="suggest"),
    re_path(r'^delete$', views.delete, name="delete"),
    re_path(r'^restore$', views.restore, name="restore"),
    re_path(r'^rename/(?P<tag>.*)$', views.rename, name="rename"),
    re_path(r'^pin/(?P<tag>.*)$', views.pin, name="pin"),
    re_path(r'^htmlBlock/(?P<tag>\d+)$', views.htmlBlock, name="htmlBlock"),
    re_path(r'^tag$', views.tag, name="tag"),
    re_path(r'^untag$', views.untag, name="untag"),
    re_path(r'^~(?P<tag>.*)$', views.filter, name="filter"),
    re_path(r'^untagged$', views.untagged, name="untagged"),
]

users/urls.py
""" URLs for user management things

URLs are:
- home
- import
- logout
- login
- register
- preview

And the URLs used by Django's password reset thing:
- reset
- resetDone
- resetConfirm/(code)
- resetComplete
"""

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse, re_path

import users.views as views

app_name="user"
urlpatterns = [
    re_path(r"^$", views.home, name="home"),
    re_path(r"^import$", views.importFile, name="import"),
    re_path(r"^pass_change$", views.pass_change, name="pass_change"),
    re_path(r"^email_change$", views.email_change, name="email_change"),
    re_path(r"^theme_change$", views.theme_change, name="theme_change"),
    
    re_path(r"^logout$", views.logout, name="logout"),
    re_path(r"^login$", views.login, name="login"),
    re_path(r"^register$", views.register, name="register"),

    re_path(r"^preview$", views.preview, name="preview"),

    re_path(r"^make_trial$", views.make_trial, name="make_trial"),
    re_path(r"^upgrade$", views.upgrade, name="upgrade"),

    re_path(r"^reset$", PasswordResetView.as_view(\
        template_name="users/reset.html", success_url="/user/resetDone",\
        email_template_name="users/reset_email.txt"
    )),
    re_path(r"^resetDone$", PasswordResetDoneView.as_view(template_name="users/reset_done.html")),
    re_path(r"^resetConfirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$", PasswordResetConfirmView.as_view(template_name="users/reset_confirm.html",\
        success_url="/user/resetComplete"\
    )),
    re_path(r"^resetComplete$", PasswordResetCompleteView.as_view(template_name="users/reset_complete.html")),
]

bmat/views.py
""" General views

At the moment this only contains the home page and the privacy policy.
"""

from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from users.views import login

def home(request):
    """ Home page is a redirect to the bookmarks list or a direct insert of the login page"""
    if request.user.is_authenticated:
        return redirect(reverse("bookmarks:home"))
    else:
        return login(request)


def privacy(request):
    """ Privacy policy, uses bmat/privacy.html """
    return TemplateResponse(request, "bmat/privacy.html", {})

bmat/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}No Title{% endblock %}</title>
        <link rel='stylesheet' href='{% static "styles.css" %}'/>
        <link rel='stylesheet' href='{% static "theme_"|add:theme|add:".css" %}' id='themeLink'
            data-prefix='{% static "theme_" %}'/>
        <style>
        .button {
            background-image:url('{% static "icons.png" %}');
        }
        </style>
        <link rel='chrome-webstore-item' href='{{ webstore_url }}'>
        
        {% if analytics_code %}
            <script>
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
                
                ga('create', "{{ analytics_code }}", 'auto');
                ga('send', 'pageview');
            </script>
        {% endif %}
        
        {% if ad_client %}
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        {% endif %}
        
        <script async src='//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'></script>
        <script async src='{% static "scripts.js" %}'></script>
        <link rel="shortcut icon" href="/static/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {% block extra_head %}{% endblock %}
    </head>
    
    <body>
        <div id='error' style='display:none'>
            <div class='errorText'>
                ERROR!
            </div>
            
            <div class='errorButtons'>
                <a class='close button'>&nbsp;</a>
            </div>
        </div>
        
        <div id='undo' style='display:none'>
            <div class='undoText'>
                
            </div>
            
            <form method='POST' id='undoForm'>
                {% csrf_token %}
                <input type='hidden' name='obj'/>
                <input type='submit' value='Undo'/>
            </form>
            
            <div class='undoButtons'>
                <a class='close button'>&nbsp;</a>
            </div>
        </div>
        
        <nav>
            {% if user.is_authenticated %}
                <a href='{% url "bookmarks:home" %}' {% if area == "bookmarks" %}class='active'{% endif %}>
                    Bookmarks
                </a>
                
                <a href='{% url "tags:home" %}' {% if area == "tags" %}class='active'{% endif %}>
                    Tags
                </a>
                
                <a href='{% url "search:home" %}' {% if area == "search" %}class='active'{% endif %}>
                    Search
                </a>
                
                {% if not user.settings.hide_settings %}
                    <a href='{% url "user:home" %}' {% if area == "user" %}class='active'{% endif %}>
                        Settings
                    </a>
                {% endif %}
                
                {% for t in pinned_tags %}
                <a href='{% url "tags:filter" tag=t.slug %}' {% if tag.pk == t.pk %}class='active'{% endif %}>
                    {{ t.name }}
                </a>
                {% endfor %}
            {% else %}
                <a href='{% url "user:login"%}' class='active'>
                    Log In
                </a>
            {% endif %}
        </nav>
        
        {% if ad_slot_top %}
        <ins class="adsbygoogle" style="display:block" data-ad-client="{{ ad_client }}" data-ad-slot="{{ ad_slot_top }}"
            data-ad-format="auto"
        ></ins>
        <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
        {% endif %}
        
        <main>
            {% if user.is_authenticated and user.settings.is_trial %}
                <div class='box underlink'>You are using a test account. If you want to upgrade to a full account and
                    keep your data, go <a href='{% url "user:upgrade" %}'>here</a>.</div>
            {% endif %}
            
            {% block content %}
                <div class='box'>No document content specified.</div>
            {% endblock %}
        </main>
        
        <footer class='underlink'>
            Website Created by <a href='mailto:bruntonross+bmat@gmail.com'>Ross Brunton</a> - 
            <a href='{% url "privacy" %}'>Privacy Policy</a> - 
            <a href='https://github.com/RossBrunton/BMAT/issues'>Bug Reports and Feature Requests</a> - 
            <a href='https://github.com/RossBrunton/BMAT/commits/master'>Changelog</a>
            {% if user.is_authenticated %}
                - <a href='{% url "user:home" %}'>Site Settings</a>
            {% endif %}
        </footer>
        
        {% if ad_slot_bottom %}
        <ins class="adsbygoogle" style="display:block" data-ad-client="{{ ad_client }}"
            data-ad-slot="{{ ad_slot_bottom }}" data-ad-format="auto"
        ></ins>
        <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
        {% endif %}
        
        <div class='hidden' id='csrf'>{{ csrf_token }}</div>
    </body>
</html>

bmat/templates/form_errors.html
{% if form.errors %}
    <div class='box form-errors'>
        {% for ek, e in form.errors.items %}
            {% for ee in e %}
                {{ ee }}<br/>
            {% endfor %}
        {% endfor %}
    </div>
{% endif %}

bmat/templates/pages.html
{% if pages.num_pages > 1 %}
    <div class='box pages'>
        {% for p in pages.page_range %}
            {% if not forloop.first %} - {% endif %}
            {% if p == current.number %} <span class='currentPage'>{{ p }}</span> 
            {% else %}
                <a href='?p={{ p }}'>{{ p }}</a>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

bmat/templates/url_add.html
<form id='add-bookmark' method="POST" style='display:flex'>
    {% csrf_token %}
    {% if tag %}<input name='tag' type='hidden' value='{{ tag }}'/>{% endif %}
    <input type='text' name='url' style='width:100%' placeholder='Add URL'/> <input type='submit' value='Add'/>
</form>