bmat/urls.py
""" Root URL config """

from django.conf.urls import include
from django.urls import path, re_path
from django.contrib import admin

import bmat.views, bookmarks.urls, users.urls, tags.urls, search.urls, autotags.urls

admin.autodiscover()

urlpatterns = [
    re_path(r'^$', bmat.views.home, name="home"),
    re_path(r'^privacy$', bmat.views.privacy, name="privacy"),
    path(r"admin/", admin.site.urls),
    
    re_path(r'^user/', include("users.urls")),
    re_path(r'^bookmarks/', include("bookmarks.urls")),
    re_path(r'^autotags/', include("autotags.urls")),
    re_path(r'^tags/', include("tags.urls")),
    re_path(r'^search/', include("search.urls")),
]

tags/urls.py
""" URLs for tag related things 

URLs are:
- home
- suggest/(query)
- delete
- rename/(tag)
- htmlBlock/(tag)
- tag
- untag
- ~(tag) (named "filter")

"""

from django.urls import re_path
import tags.views as views

app_name="tags"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    
    re_path(r'^suggest/(?P<value>.*)$', views.suggest, name="suggest"),
    re_path(r'^delete$', views.delete, name="delete"),
    re_path(r'^restore$', views.restore, name="restore"),
    re_path(r'^rename/(?P<tag>.*)$', views.rename, name="rename"),
    re_path(r'^pin/(?P<tag>.*)$', views.pin, name="pin"),
    re_path(r'^htmlBlock/(?P<tag>\d+)$', views.htmlBlock, name="htmlBlock"),
    re_path(r'^tag$', views.tag, name="tag"),
    re_path(r'^untag$', views.untag, name="untag"),
    re_path(r'^~(?P<tag>.*)$', views.filter, name="filter"),
    re_path(r'^untagged$', views.untagged, name="untagged"),
]

tags/forms.py
""" Forms for manipulating tags """
from django import forms

from tags.models import Tag, colours_enum

class ColourSelect(forms.widgets.ChoiceWidget):
    input_type = "input"
    template_name = "tags/forms/colourSelect.html"
    option_template_name = "tags/forms/colourSelectOption.html"
    checked_attribute = {"data-selected": True}
    option_inherits_attrs = False

class RenameTagForm(forms.ModelForm):
    """ A model form for renaming a tag
    
    It requires the fields "colour" and "name".
    """
    class Meta:
        model = Tag
        fields = ["colour", "name"]
    
    colour = forms.ChoiceField(choices=colours_enum, widget=ColourSelect)

class PinTagForm(forms.ModelForm):
    """ A model form for pinning and unpinning a tag
    
    It requires the "pinned" field.
    """
    class Meta:
        model = Tag
        fields = ["pinned"]


class AddTagForm(forms.ModelForm):
    """ A model form for adding a new tag
    
    It requires the fields "colour" and "name". It also has additional fields "type" and "pk", which are the type and
    primary key of the thing to be tagged as well.
    """
    class Meta:
        model = Tag
        fields = ["colour", "name"]
    
    def __init__(self, *args, **kwargs):
        super(AddTagForm, self).__init__(*args, **kwargs)
        
        self.type_str = args[0].get("type")
    
    type = forms.CharField()
    pk = forms.IntegerField(min_value=1)
    colour = forms.ChoiceField(choices=colours_enum, widget=ColourSelect)


class RemoveTagForm(forms.Form):
    """ A form for removing a tag
    
    It requires the fields "tag_pk", "type" and "target_pk". "type" and "target_pk" describe the thing that will be
    untagged, while "tag_pk" is the primary key of the tag to untag.
    """
    tag_pk = forms.IntegerField(min_value=1)
    type = forms.CharField()
    target_pk = forms.IntegerField(min_value=1)

tags/views.py
""" View functions for tag related things

This includes both viewing the tag list, and manipulating tags on other things.
"""
from django.contrib.auth.decorators import login_required
from django.core.exceptions import SuspiciousOperation
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template import defaultfilters
from django.template.response import TemplateResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from tags.models import Tag
from tags.forms import AddTagForm, RemoveTagForm, RenameTagForm, PinTagForm
import tags
from tags import makeslug
from bookmarks.models import Bookmark
from .templatetags.tag import tagBlock
from bmat.utils import make_page

import json

@login_required
def home(request):
    """ Uses index.html to display a list of all the user's tags """
    ctx = {}
    
    ctx["area"] = "tags"
    ctx["tags"] = make_page(Tag.by_user(request.user), request.GET.get("p"))
    ctx["untag_count"] = Bookmark.by_user(request.user).filter(tags=None).count()
    
    return TemplateResponse(request, "tags/index.html", ctx)


@login_required
def filter(request, tag):
    """ Given a slug, uses filter.html to display all the things tagged with that specific tag """
    tag = get_object_or_404(Tag, owner=request.user, slug=makeslug(tag))
    
    ctx = {}
    
    if not tag.pinned:
        # Don't display "tags" thing as active when the tag is pinned
        ctx["area"] = "tags"
    
    ctx["tag"] = tag
    ctx["pin_form"] = PinTagForm(instance=tag)
    ctx["bookmarks"] = make_page(Bookmark.get_by_tag(tag), request.GET.get("p"))
    
    return TemplateResponse(request, "tags/filter.html", ctx)

@login_required
def untagged(request):
    """ Given a slug, uses filter.html to display all the things tagged with that specific tag """
    
    ctx = {}
    bookmarks = Bookmark.by_user(request.user).filter(tags=None)
    ctx["untag_count"] = bookmarks.count()
    ctx["area"] = "tags"
    ctx["tag"] = None
    ctx["bookmarks"] = make_page(bookmarks, request.GET.get("p"))
    
    return TemplateResponse(request, "tags/filter.html", ctx)

@login_required
def suggest(request, value):
    """ Returns a JSON object containing tag suggestions for the sepecified value
    
    The JSON object contains two values:
    - yours: The string that was submitted to this page
    - tags: An array of strings for the suggestions
    """
    tags = Tag.objects.filter(owner=request.user, slug__startswith=makeslug(value))[:10]
    
    return TemplateResponse(request, "tags/suggest.json", {"tags":tags, "value":value}, "application/json")


@login_required
@require_POST
def tag(request):
    """ Tags a thing using an AddTagForm
    
    Returns a JSON response with an "obj" and "key" porperty. "obj" is the object that was tagged, while "type" is it's
    type. If there is an error, a JSON object with an "error" key is returned instead.
    """
    f = AddTagForm(request.POST)
    
    if not f.is_valid():
        return HttpResponse('{"error":"Form invalid"}', content_type="application/json", status=422)
    
    taggable = tags.lookup_taggable(f.cleaned_data["type"])
    
    if taggable is None:
        return HttpResponse('{"error":"Taggable type invalid"}', content_type="application/json", status=422)
    
    try:
        obj = taggable.objects.get(owner=request.user, pk=f.cleaned_data["pk"])
    except taggable.DoesNotExist:
        return HttpResponse('{"error":"Taggable not found"}', content_type="application/json", status=422)
    
    tag_names = map(lambda x: x.strip(), f.cleaned_data["name"].split(","))
    
    for n in tag_names:
        if not n:
            continue
        
        try:
            tag = Tag.objects.get(owner=request.user, slug=makeslug(n))
        except Tag.DoesNotExist:
            tag = Tag(owner=request.user, name=n, colour=f.instance.colour)
            tag.save()
        
        obj.tag(tag)
    
    return HttpResponse(
        '{{"obj":{}, "type":"{}"}}'.format(obj.to_json(), f.cleaned_data["type"]),
        content_type="application/json"
    )


@login_required
@require_POST
def untag(request):
    """ Untags a thing using a RemoveTagForm
    
    Returns a JSON response with a "deleted" and "key" porperty. "deleted" is the primary key of the object that had
    its tag removed, while "type" is it's type. If there is an error, a JSON object with an "error" key is returned
    instead.
    """
    f = RemoveTagForm(request.POST)
    
    if not f.is_valid():
        return HttpResponse('{"error":"Form invalid"}', content_type="application/json", status=422)
    
    taggable = tags.lookup_taggable(f.cleaned_data["type"])
    if taggable is None:
        return HttpResponse('{"error":"Taggable type invalid"}', content_type="application/json", status=422)
    
    try:
        obj = get_object_or_404(taggable, owner=request.user, pk=f.cleaned_data["target_pk"])
    except taggable.DoesNotExist:
        return HttpResponse('{"error":"Taggable not found"}', content_type="application/json", status=422)
    
    try:
        tag = Tag.objects.get(owner=request.user, pk=f.cleaned_data["tag_pk"])
    except Tag.DoesNotExist:
        return HttpResponse('{"error":"Tag to remove not found"}', content_type="application/json", status=422)
    
    obj.tags.remove(tag)
    
    return HttpResponse(
        '{{"deleted":{}, "type":"{}"}}'.format(obj.pk, f.cleaned_data["type"]), content_type="application/json"
    )


@login_required
@require_POST
def restore(request):
    """ Given the undoable json representation of a bookmark, performs the undo, recovering the tag
    
    The tag must have been from "undoable_json", and must be the "obj" POST value.
    
    If it succeeds it returns a JSON object with "obj" being the JSON representation of the bookmark, "type" which
    is always "tag" and "id" which is the id of the newly created bookmark.
    """
    if "obj" not in request.POST:
        raise SuspiciousOperation
    
    try:
        tag = Tag.from_undoable(request.POST.get("obj"), request.user)
    except Exception:
        raise SuspiciousOperation
    
    out = {}
    out["type"] = "tag"
    out["obj"] = tag.to_json()
    out["id"] = tag.pk
    
    return HttpResponse(json.dumps(out), content_type="application/json")


@login_required
@require_POST
def delete(request):
    """ Deletes a tag
    
    The primary key of the tag must be specified with the "tag" POST value. If the tag doesn't exist, nothing happens.
    
    This returns a JSON object with the following properties:
    deleted: The primary key of the deleted tag, or null if it didn't exist.
    obj: The JSON representation of the deleted tag, or null if it didn't exist.
    alreadyDeleted: True if and only if the tag was deleted before this request.
    type: Always "tag".
    """
    if "tag" not in request.POST:
        raise SuspiciousOperation
    
    try:
        tag = Tag.objects.get(owner=request.user, pk=request.POST["tag"])
    except Tag.DoesNotExist:
        return HttpResponse(
            '{"deleted":null, "obj":null, "alreadyDeleted":true, "type":"tag"}', content_type="application/json"
        )
    
    id = tag.pk
    json = tag.undoable_json()
    tag.delete()
    
    return HttpResponse(
        '{"deleted":'+str(id)+', "obj":'+json+', "alreadyDeleted":false, "type":"tag"}',
        content_type="application/json"
    )


@login_required
def htmlBlock(request, tag):
    """ Outputs the HTML for a tag block, such as for the tags list page
    
    This uses the tagBlock.html temlpate.
    """
    tag = get_object_or_404(Tag, pk=tag, owner=request.user)
    
    return TemplateResponse(request, "tags/tagBlock.html", tagBlock(tag))


@login_required
@require_POST
def rename(request, tag):
    """ Renames a tag using a RenameTagForm
    
    If successfull, outputs a JSON object with "obj", "type" and "pooled" properties. "obj" is the JSON object of the
    tag that was renamed, while "type" will always be "tag". pooled is true when the tag has been renamed to that of an
    existing tag, in which case "obj" will be that tag. 
    
    If it fails, a JSON object with an "error" value will be returned.
    """
    tagObj = get_object_or_404(Tag, owner=request.user, slug=tag)
    
    form = RenameTagForm(request.POST, instance=tagObj)
    
    if not form.is_valid():
        return HttpResponse('{"error":"Form invalid"}', content_type="application/json", status=422)
    
    if Tag.objects.filter(owner=request.user, slug=makeslug(form.data["name"])).exclude(pk=form.instance.pk).exists():
        # Tag exists, pool them
        existing = Tag.objects.get(owner=request.user, slug=makeslug(form.data["name"]))
        form.instance.pool_into(existing)
        form.instance.delete()
        tagObj = existing
        pooled = "true"
    else:
        form.save()
        pooled = "false"
    
    return HttpResponse('{"obj":'+tagObj.to_json()+', "type":"tag", "pooled":'+pooled+'}',
        content_type="application/json")


@login_required
@require_POST
def pin(request, tag):
    """ Updates a tags pinning using a PinTagForm
    
    If successfull, outputs a JSON object with "obj" and "type" properties. "obj" is the JSON object of the tag that was
    renamed, while "type" will always be "tag".
    
    If it fails, a JSON object with an "error" value will be returned.
    """
    tagObj = get_object_or_404(Tag, owner=request.user, slug=tag)
    
    form = PinTagForm(request.POST, instance=tagObj)
    
    if not form.is_valid():
        return HttpResponse('{"error":"Form invalid"}', content_type="application/json", status=422)
    
    form.save()
    
    return HttpResponse('{"obj":'+tagObj.to_json()+', "type":"tag"}', content_type="application/json")

tags/templates/tags/addTag.html
{% load tag %}
<form class='tagForm' style='display:flex' method='POST' action='{% url "tags:tag" %}'>
    {% csrf_token %}
    {{ atf.type.as_hidden }}
    <input type='hidden' name='pk' value='{{ pk }}' />
    <input class='tagEntry' type='text' placeholder='Add Tag' name='name' list='tslist-{{ atf.type_str }}-{{ pk }}'/>
    <datalist id='tslist-{{ atf.type_str }}-{{ pk }}'>
        
    </datalist>
    {{ atf.colour }}
    <a class='addTag button rightSpace' title='Add Tag'>&nbsp;&nbsp;&nbsp;</a>
</form>

tags/templates/tags/filter.html
{% extends "base.html" %}

{% load tag bookmark url_add pages %}

{% block title %}{% if tag %}Tag: {{ tag.name }}{% else %}Untagged{% endif %}{% endblock %}

{% block content %}

{% if tag %}
    <div class='box flex'>
        {% multiTagButton %}
        {% url_add tag %}
        <form action='{% url "tags:pin" tag=tag.slug %}' method='POST' id='pinForm' class='flex'>{% csrf_token %}
            {% if tag.pinned %}
                <input type='submit' value='Remove this tag from the top bar'/>
            {% else %}
                <input type='hidden' name='pinned' value='on'/>
                <input type='submit' value='Pin this tag so it appears in the top bar'/>
            {% endif %}
        </form>
    </div>

    {% multiTag "bookmark" %}
    
    {% tagBlock tag %}
{% else %}
    <div class='tagBlock box block white'>
        <div class='head'>
            <div class='title'><a href='{% url "tags:untagged" %}'>Untagged</a></div>
            <span class='count'>{{ untag_count }}</span>
        </div>
    </div>
    
    {% multiTag "bookmark" automulti=True %}
{% endif %}

<div id='bookmark-list'>
    {% for bm in bookmarks %}
        {% if tag %}
            {% bookmark bm tag %}
        {% else %}
            {% bookmark bm tag automulti=True %}
        {% endif %}
    {% endfor %}
</div>

{% pages bookmarks "" %}
{% endblock %}

tags/templates/tags/index.html
{% extends "base.html" %}
{% load tag pages %}

{% block title %}Tags{% endblock %}

{% block content %}
<div id='tag-list'>
    <div class='tagBlock box block white'>
        <div class='head'>
            <div class='title'><a href='{% url "tags:untagged" %}'>Untagged</a></div>
            <span class='count'>{{ untag_count }}</span>
        </div>
    </div>
    
    {% for tag in tags %}
        {% tagBlock tag %}
    {% empty %}
        <div class='box'>
            You have no tags; add some by going to a bookmark, clicking the settings button and entering one there.
        </div>
    {% endfor %}
</div>

{% pages tags "tags:home" %}
{% endblock %}

tags/templates/tags/multiTag.html
{% load tag %}
<div class='{% if not automulti %}multiTagBox {% endif %}box'>
    <div class='flex'>
        <div><a class='multiTagAll button' title='Select All'>&nbsp;</a></div>
        <form class='multiTagForm flex'>
            <input class='tagEntry' type='text' placeholder='Add Tag' name='name' list='tslist-multi'/>
            <datalist id='tslist-multi'>
                
            </datalist>
            {{ atf.colour }}
            <input type='submit' class='padLeft' value='Add tag to all selected'/> 
        </form>
    </div>
</div>

tags/templates/tags/multiTagButton.html
{% load tag %}
<div><a class='multiTag button' title='Tag Multiple'>&nbsp;</a></div>

tags/templates/tags/tag.html
<div class='tag {{ tag.colour }}' data-id='{{ tag.pk }}' data-slug='{{ tag.slug }}'>
    <a href='{% url "tags:filter" tag=tag.slug %}'>{{ tag.name }}</a>
    {% if direct %}
    <form action='{% url "tags:untag" %}' method='POST' class='inlineUntagForm'>
        {% csrf_token %}
        {{ rtf.type.as_hidden }}
        <input type='hidden' name='tag_pk' value='{{ tag.pk }}' />
        <input type='hidden' name='target_pk' value='{{ pk_target }}' />
        <a class='inlineUntag button' title='Remove Tag'>&nbsp;</a>
    </form>
    
    {% endif %}
</div>

tags/templates/tags/tagBlock.html
{% load tag %}
<div class='tagBlock box block {{ tag.colour }}' data-id='{{ tag.pk }}' data-slug='{{ tag.slug }}'
data-taggable-type='tag'>
    <div class='head'>
        <div class='title noedit'><a href='{% url "tags:filter" tag=tag.slug %}'>{{ tag.name }}</a></div>
        
        <div class='title edit'>
            <form class='renameForm' method='POST' action='{% url "tags:rename" tag=tag.slug %}'>
                {% csrf_token %}
                <input class='renameEntry' name='name' type='text' value='{{ tag.name }}'/>
                {{ renametf.colour }}
            </form>
        </div>
        
        <span class='count'>{{ tag.bookmarks.all.count }}</span>
        
        <div class='tags nomobile'>{% for t in implies %}{% tag t tag %}{% endfor %}</div>
        
        <div class='buttons'>
            <a class='expand button' title='Show Options'>&nbsp;</a>
        </div>
    </div>
    <div class='head mobile'>
        <div class='tags'>{% for t in implies %}{% tag t tag %}{% endfor %}</div>
    </div>
    
    <div class='body' style='display:none'>
        <div class='nomobile'>{% for t in tag.tags_to.all %}{% tag t tag %}{% endfor %}</div>
        
        <div class='rightIfNotMobile'>{% addTag "tag" tag.pk %}</div>
        
        <div class='padLeft buttons rightIfMobile'>
            <a class='rename button edit' style='display:none' title='Save'>&nbsp;</a>
            <a class='editTitle button noedit' title='Edit'>&nbsp;</a>
            
            <form action='{% url "tags:delete" %}' method='POST' class='deleteForm'
                data-undo-url='{% url "tags:restore" %}' data-undo-name='Tag'
            >
                {% csrf_token %}
                <input type='hidden' name='tag' value='{{ tag.pk }}'/>
                <a class='delete button' title='Delete'>&nbsp;</a>
            </form>
        </div>
    </div>
</div>