autotags/urls.py
""" URLs for autotag related things

URLs are:
- home
- add
- delete
- (autotag)/html
- (autotag)/setPattern

"""

from django.urls import re_path
import autotags.views as views

app_name="autotags"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^add$', views.add, name="add"),
    re_path(r'^delete$', views.delete, name="delete"),
    re_path(r'^create$', views.create, name="create"),
    re_path(r'^check$', views.check, name="check"),
    
    re_path(r'^(?P<autotag>[0-9]+)/html$', views.html, name="html"),
    re_path(r'^(?P<autotag>[0-9]+)/setPattern$', views.setPattern, name="setPattern"),
]

bmat/urls.py
""" Root URL config """

from django.conf.urls import include
from django.urls import path, re_path
from django.contrib import admin

import bmat.views, bookmarks.urls, users.urls, tags.urls, search.urls, autotags.urls

admin.autodiscover()

urlpatterns = [
    re_path(r'^$', bmat.views.home, name="home"),
    re_path(r'^privacy$', bmat.views.privacy, name="privacy"),
    path(r"admin/", admin.site.urls),
    
    re_path(r'^user/', include("users.urls")),
    re_path(r'^bookmarks/', include("bookmarks.urls")),
    re_path(r'^autotags/', include("autotags.urls")),
    re_path(r'^tags/', include("tags.urls")),
    re_path(r'^search/', include("search.urls")),
]

bookmarks/urls.py
""" URLs for bookmark related things 

URLs are:
- home
- export (For exporting bookmarks to HTML that browsers can import)
- add
- delete
- (bookmark)/html
- (bookmark)/rename

"""

from django.urls import re_path

import bookmarks.views as views

app_name="bookmarks"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^export$', views.export, name="export"),
    re_path(r'^add$', views.add, name="add"),
    re_path(r'^delete$', views.delete, name="delete"),
    re_path(r'^create$', views.create, name="create"),
    
    re_path(r'^(?P<bookmark>[0-9]+)/html$', views.html, name="html"),
    re_path(r'^(?P<bookmark>[0-9]+)/rename$', views.rename, name="rename"),
]

search/urls.py
""" URLs for searching

URLs are:
- home
- results (for the AJAX stuff)

"""

from django.urls import re_path
import search.views as views

app_name="search"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^results$', views.results, name="results"),
]

tags/urls.py
""" URLs for tag related things 

URLs are:
- home
- suggest/(query)
- delete
- rename/(tag)
- htmlBlock/(tag)
- tag
- untag
- ~(tag) (named "filter")

"""

from django.urls import re_path
import tags.views as views

app_name="tags"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    
    re_path(r'^suggest/(?P<value>.*)$', views.suggest, name="suggest"),
    re_path(r'^delete$', views.delete, name="delete"),
    re_path(r'^restore$', views.restore, name="restore"),
    re_path(r'^rename/(?P<tag>.*)$', views.rename, name="rename"),
    re_path(r'^pin/(?P<tag>.*)$', views.pin, name="pin"),
    re_path(r'^htmlBlock/(?P<tag>\d+)$', views.htmlBlock, name="htmlBlock"),
    re_path(r'^tag$', views.tag, name="tag"),
    re_path(r'^untag$', views.untag, name="untag"),
    re_path(r'^~(?P<tag>.*)$', views.filter, name="filter"),
    re_path(r'^untagged$', views.untagged, name="untagged"),
]

users/urls.py
""" URLs for user management things

URLs are:
- home
- import
- logout
- login
- register
- preview

And the URLs used by Django's password reset thing:
- reset
- resetDone
- resetConfirm/(code)
- resetComplete
"""

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse, re_path

import users.views as views

app_name="user"
urlpatterns = [
    re_path(r"^$", views.home, name="home"),
    re_path(r"^import$", views.importFile, name="import"),
    re_path(r"^pass_change$", views.pass_change, name="pass_change"),
    re_path(r"^email_change$", views.email_change, name="email_change"),
    re_path(r"^theme_change$", views.theme_change, name="theme_change"),
    
    re_path(r"^logout$", views.logout, name="logout"),
    re_path(r"^login$", views.login, name="login"),
    re_path(r"^register$", views.register, name="register"),

    re_path(r"^preview$", views.preview, name="preview"),

    re_path(r"^make_trial$", views.make_trial, name="make_trial"),
    re_path(r"^upgrade$", views.upgrade, name="upgrade"),

    re_path(r"^reset$", PasswordResetView.as_view(\
        template_name="users/reset.html", success_url="/user/resetDone",\
        email_template_name="users/reset_email.txt"
    )),
    re_path(r"^resetDone$", PasswordResetDoneView.as_view(template_name="users/reset_done.html")),
    re_path(r"^resetConfirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$", PasswordResetConfirmView.as_view(template_name="users/reset_confirm.html",\
        success_url="/user/resetComplete"\
    )),
    re_path(r"^resetComplete$", PasswordResetCompleteView.as_view(template_name="users/reset_complete.html")),
]

users/forms.py
""" Forms for user management """
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from users.models import Settings

class ThemeSelect(forms.widgets.ChoiceWidget):
    input_type = "input"
    template_name = "users/forms/themeSelect.html"
    option_template_name = "users/forms/themeSelectOption.html"
    checked_attribute = {"data-selected": True}
    option_inherits_attrs = False

class ImportForm(forms.Form):
    """ The form used to import a bookmark file """
    use_tags = forms.BooleanField(required=False)
    file = forms.FileField()

class CustomUserCreationForm(UserCreationForm):
    """ Subclass of the normal UserCreationForm to add an optional email """
    email = forms.EmailField(required=False)

class SettingsForm(forms.ModelForm):
    """ And a form to edit settings """
    class Meta:
        model = Settings
        fields = ("url_settings", "no_analytics", "hide_settings")

class ThemeForm(forms.ModelForm):
    """ And a form to edit theme settings """
    class Meta:
        model = Settings
        fields = ("theme",)
    
    theme = forms.ChoiceField(choices=Settings.THEME_OPTIONS, widget=ThemeSelect)

class EmailForm(forms.ModelForm):
    """ And a form to edit settings, specifically the theme """
    class Meta:
        model = User
        fields = ("email",)

users/views.py
""" View functions for user management """

from django.contrib.auth import logout as alogout, login as alogin, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.response import TemplateResponse
from django.views.decorators.http import require_POST
from django.forms.utils import ErrorList
from django.urls import reverse

from django.conf import settings
from bookmarks.models import Bookmark
from users.forms import ImportForm, CustomUserCreationForm, SettingsForm, EmailForm, ThemeForm
from users.utils import clean_trial, make_trial_user

import random
import string
import re, datetime

try:
    import html
except ImportError:
    html = None
    import HTMLParser

def _unescape(text):
    if html:
        return html.unescape(text)
    else:
        return HTMLParser.HTMLParser().unescape(text)

def _make_context(request, form_name, form_value):
    ctx = {}
    
    # TODO: Is creating forms expensive
    ctx["area"] = "user"
    ctx["importForm"] = ImportForm()
    ctx["pass_form"] = PasswordChangeForm(request.user)
    ctx["email_form"] = EmailForm(instance=request.user)
    ctx["settings_form"] = SettingsForm(instance=request.user.settings)
    ctx["theme_form"] = ThemeForm(instance=request.user.settings)
    
    ctx[form_name] = form_value
    
    return ctx

@login_required
def home(request, note=""):
    """ The settings page for users
    
    If you post a SettingsForm to this, it will be saved. In all cases, it renders index.html to provide the user some
    account managment things.
    
    This view may also take a note, in which case the note will be displayed at the top of the page and the request
    will run as if it were a GET.
    """
    if request.method == "POST" and not note:
        form = SettingsForm(request.POST, instance=request.user.settings)
        if form.is_valid():
            form.save()
            note = "Settings Updated Successfully"
        
    else:
        form = SettingsForm(instance=request.user.settings)
    
    ctx = _make_context(request, "settings_form", form)
    ctx["note"] = note
    
    return TemplateResponse(request, "users/index.html", ctx)


@login_required
def pass_change(request):
    """ The password change page
    
    If you pass it a Django PasswordChangeForm, it will save it, and display a message. If it fails, it renders the
    users home page.
    """
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return home(request, "Password Changed Successfully")
    
    else:
        form = PasswordChangeForm(instance=request.user)
    
    ctx = _make_context(request, "pass_form", form)
    
    return TemplateResponse(request, "users/index.html", ctx)

@login_required
def email_change(request):
    """ The email change page
    
    If you pass it an EmailForm, it will save it, and display a message. If it fails, it renders the users home page.
    """
    if request.method == "POST":
        form = EmailForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return home(request, "Email Changed Successfully")
    
    else:
        form = EmailForm(instance=request.user)
    
    ctx = _make_context(request, "email_form", form)
    
    return TemplateResponse(request, "users/index.html", ctx)

@login_required
def theme_change(request):
    """ The theme change page
    
    If you pass it a ThemeForm, it will save it, and display a message. If it fails, it renders the users home page.
    """
    if request.method == "POST":
        form = ThemeForm(request.POST, instance=request.user.settings)
        if form.is_valid():
            form.save()
            return home(request, "Theme Changed Successfully")
    else:
        form = ThemeForm(instance=request.user.settings)
    
    ctx = _make_context(request, "theme_form", form)
    
    return TemplateResponse(request, "users/index.html", ctx)

@require_POST
@login_required
def importFile(request):
    """ When sent an ImportForm, will import the bookmarks from the file
    
    Outputs the users/index.html on error with the appropriate form. If it succeeds, it redirects to the home page. This
    behaviour should probably be changed at some point.
    """
    
    form = ImportForm(request.POST, request.FILES)
    
    error = False
    
    def add_error(message):
        error_list = form._errors.setdefault("file", ErrorList())
        error_list.append(message)
    
    if not form.is_valid():
        error = True
    
    if not error and request.FILES["file"].multiple_chunks():
        add_error("File too large")
        error = True
    
    if not error:
        try:
            _handle_import(request.FILES["file"].read(), form.data.get("use_tags", False), request.user)
        except:
            add_error("File is invalid or not of a supported format")
            error = True
    
    if error:
        ctx = _make_context(request, "importForm", form)
        
        return TemplateResponse(request, "users/index.html", ctx, status=422)
    
    return HttpResponseRedirect("/")


@require_POST
@login_required
def logout(request):
    """ Logs the user out and redirects them to the home page """
    alogout(request)
    
    return HttpResponseRedirect("/")

@login_required
def preview(request):
    """ The preview page for themes
    
    Set the theme with the "t" GET attribute
    """
    ctx = {}
    
    ctx["area"] = "bookmarks"
    ctx["preview_theme"] = request.GET.get("t", "light")
    ctx["bookmarks"] = Bookmark.by_user(request.user)[:5]
    
    return TemplateResponse(request, "users/preview.html", ctx)


def login(request):
    """ Either displays or handles a login request
    
    If an AuthenticationForm is posted, the user will be logged in and be redirect to the value of the "next" GET value
    if it exists, otherwise they will be redirected to the home page.
    
    If this page is requested via GET, it just displays a log in form.
    
    This also deletes any expired trial users, since I have no idea where else to put it.
    """
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            clean_trial()
            alogin(request, form.get_user())

            return HttpResponseRedirect(request.GET.get("next", reverse("bookmarks:home")))
    else:
        form = AuthenticationForm(request)

    register_form = CustomUserCreationForm()

    context = {
        'form': form,
        'reg_form': register_form,
        'can_register': settings.BMAT_ALLOW_REGISTER
    }
    
    return TemplateResponse(request, "users/login.html", context)


def register(request):
    """ Either registers a new user, displays a registration form or tells the user that they can't register
    
    If the setting BMAT_ALLOW_REGISTER is false, then this renders the template no_register.html and does nothing with
    any POST data.
    
    This uses the register.html template if users are allowed to register.
    """
    if not settings.BMAT_ALLOW_REGISTER:
        return render(request, "users/no_register.html", {})
    
    if request.method == "GET":
        return render(request, "users/register.html", {"form":CustomUserCreationForm()})
    
    elif request.method == "POST":
        f = CustomUserCreationForm(data=request.POST)
        
        if not f.is_valid():
            return render(request, "users/register.html", {"form":f})
        
        u = f.save(commit=False)
        
        u.email = f.cleaned_data.get("email", "")
        u.save()
        
        u = authenticate(username=u.username, password=f.cleaned_data["password1"])
        alogin(request, u)
    
    return redirect("/")


@require_POST
def make_trial(request):
    if not settings.BMAT_ALLOW_REGISTER:
        return render(request, "users/no_register.html", {})
    
    user = make_trial_user()
    alogin(request, user)
    
    return redirect("/")


@login_required
def upgrade(request):
    if not request.user.settings.is_trial:
        raise SuspiciousOperation
    
    if not settings.BMAT_ALLOW_REGISTER:
        return render(request, "users/no_register.html", {})
    
    if request.method == "POST":
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            request.user.username = form.cleaned_data["username"]
            request.user.set_password(form.cleaned_data["password1"])
            request.user.email = form.cleaned_data.get("email", "")
            request.user.settings.is_trial = False
            request.user.settings.save()
            request.user.save()

            return HttpResponseRedirect(request.GET.get("next", "/"))
    else:
        form = CustomUserCreationForm()
    
    context = {
        "form": form,
        "upgrade": True
    }
    
    return TemplateResponse(request, "users/register.html", context)


def _handle_import(contents, use_tags, owner):
    """ Handles the import of a bookmarks file
    
    Loops through all links in the file and adds them as bookmarks. It then tags them if the file contains tags and
    "use_tags" is true.
    """
    
    lines = contents.decode("utf-8").split("\n")
    
    title = re.compile(r"<a.*?>(.+?)</a>", re.I)
    url = re.compile(r"""<a.*href=['"](.+?)['"]""", re.I)
    tags = re.compile(r"""<a.*?tags=["'](.+?)["']""", re.I)
    addTime = re.compile(r"""<a.*?add_date=["'](\d+?)["']""", re.I)
    
    for l in lines:
        if "<a" in l.lower() and "</a>" in l.lower():
            bookmark = {}
            
            bookmark["title"] = title.search(l)
            if not bookmark["title"]:
                continue

users/templates/users/index.html
{% extends "base.html" %}
{% load form_errors static %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}

{% if note %}
<div class='box center yellow'>
    {{ note }}
</div>
{% endif %}

<div class='settings'>
<section class='settings-section'>
<div class='box title'>
    Account Settings
</div>

<div class='box center'>
    You are logged in as {{ user.username }}.<br/>
    <form action='{% url "user:logout" %}' method='POST'>
        {% csrf_token %}
        <input type='submit' value='Log Out'/>
    </form>
</div>

{% if not user.settings.is_trial %}
    {% form_errors pass_form %}
    <div class='box center'>
        <form method='POST' action='{% url "user:pass_change" %}'>
            {% csrf_token %}
            Change Password<br/><br/>
            <label>Old Password<br/>
                {{ pass_form.old_password }}</label><br/>
            <label>New Password<br/>
                {{ pass_form.new_password1 }}</label><br/>
            <label>Type it Again<br/>
                {{ pass_form.new_password2 }}</label><br/>
            <br/>
            <input type='submit' value='Change Password'/>
        </form>
    </div>
    
    {% form_errors email_form %}
    <div class='box center'>
        <form method='POST' action='{% url "user:email_change" %}'>
            {% csrf_token %}
            Here you can set or change an email for use when sending password reset emails<br/><br/>
            <label>Email<br/>
                {{ email_form.email }}</label><br/>
            <br/>
            <input type='submit' value='Change Email'/>
        </form>
    </div>
{% endif %}
</section>

<section class='settings-section'>
<div class='box title'>
    Site Settings
</div>

{% form_errors settings_form %}
<div class='box center'>
    <form method='POST' action='{% url "user:home" %}'>
        {% csrf_token %}
        <label>Invalid URL Handling<br/>
            {{ settings_form.url_settings }}</label><br/><br/>
        <label>{{ settings_form.no_analytics }} Opt out of anonymous usage tracking</label><br/>
        <label>{{ settings_form.hide_settings }} Hide settings button on navbar (you can access it from the bottom of the page)
        </label><br/><br/>
        <input type='submit' value='Update Settings'/>
    </form>
</div>

<div class='box center'>
    You can automatically set up rules that automatically tag newly added bookmarks.<br/><br/>
    
    <button onclick='document.location="{% url "autotags:home" %}"'>Configure Autotag Settings</button>
</div>

{% if webstore_url %}
<div class='box center hidden chrome-extension'>
    You can install a browser extension that allows you to add bookmarks directly from a page.<br/><br/>
    
    <button id='chrome-extension-install'>BMAT Extension</button>
</div>
{% endif %}

<div class='box center hidden firefox-extension'>
    You can install a browser extension that allows you to add bookmarks directly from a page.<br/><br/>
    
    <button id='firefox-extension-install' data-path='{% static "bmat.xpi" %}'>BMAT Extension</button>
</div>
</section>
</div>

<div class='box title'>
    Site Theme
</div>

<div class='box center'>
    <form action='{% url "user:theme_change" %}' method='POST'>
        {% csrf_token %}
        {{ theme_form.theme }}
        <input type='submit' value='Set Theme'/>
    </form>
</div>

<div class='box title'>
    Import and Export
</div>

{% form_errors importForm %}
<div class='box center'>
    This allows you to import bookmarks from another application or browser. When exporting from them, you should be
    given a &quot;html&quot; file, simply select that file here and click import.<br/><br/>
    
    Note that not all applications include information about tags, so clicking "Include Tags" may not do anything. In
    addition, information about tags, such as their colour and links to other tags is never included, even if you
    export bookmarks from BMAT.<br/><br/>
    
    <form enctype='multipart/form-data' action='{% url "user:import" %}' method='POST'>
        {% csrf_token %}
        {{ importForm.file }}<br/>
        <label>{{ importForm.use_tags }} Include Tags</label><br/><br/>
        <input type='submit' value='Import Bookmarks From HTML'/>
    </form>
</div>

<div class='box center'>
    You can export your bookmarks here by clicking the button below and saving the page. The saved file can then be
    imported into other browsers or applications.<br/><br/>
    
    <a class='hidden' id='exportLink' href='{% url "bookmarks:export" %}' download='Bookmark.htm'>&nbsp;</a>
    <button onclick='$("#exportLink")[0].click()'>Export Bookmarks To HTML</button>
</div>

{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% load form_errors static %}

{% block title %}BMAT - A Lightweight Bookmarks Manager{% endblock %}

{% block content %}

<div class='box title' style='font-size:150%'>
    BMAT - A Lightweight Bookmarks Manager
</div>

<div class='box pitch underlink'>
    <div class='text'>
        BMAT is a free open source lightweight website that allows you to manage your bookmarks with the following features:
        <ul>
            <li>Tag bookmarks in order to categorise them.</li>
            <li>Colour-code these tags, and add them to the navigation bar for easy access.</li>
            <li>Allow tagging a bookmark with one tag to apply related tags.</li>
            <li>Automatically tag a bookmark based on its URL when you add it.</li>
            <li>Search your bookmarks and tags.</li>
            <li>Add bookmarks directly from a site using a browser extension.</li>
            <li>No social media integration; there are no &quot;share&quot; buttons telling you how popular your private
                bookmarks are.</li>
        </ul>
    </div>
    
    <div class='image'>
        <img alt='Screenshot of Application' src='{% static "Pitch.png" %}'/>
    </div>
</div>

{% comment %}<div class='box underlink'>
    This is a web application that allows you to manage your bookmarks across multiple devices. It has the following
    features:
    <ul>
        <li>Bookmarks can be tagged into categories!</li>
        <li>Those categories can also be tagged themselves. So if you have a category &quot;dogs&quot; you can tag it
        &quot;animals&quot; and anything tagged &quot;dogs&quot; will also be tagged &quot;animals&quot;!</li>
        <li>You can search your bookmarks and tags!</li>
        <li>No social media integration! No &quot;like&quot; buttons everywhere, no counters saying how popular websites
        are, nothing.</li>
    </ul>
</div>{% endcomment %}

{% form_errors form %}
{% form_errors reg_form %}

<section class='login-options'>
<div class='box underlink center'>
    <form method='POST'>
        {% csrf_token %}
        <div class='box title'>Log In</div>
        <label>Username<br/>
            {{ form.username }}</label><br/>
        <label>Password<br/>
            {{ form.password }}</label><br/>
        <input type='submit' value='Log In'/>
    </form>
    <br/>
    <br/><button onclick='document.location="/user/reset"'>Password Reset</button>
</div>

{% if can_register %}
    <div class='box center'>
        <div class='box title'>Register</div>
        
        <form method='POST' action='/register'>
            {% csrf_token %}
            <label>Username<br/>
                {{ reg_form.username }}</label><br/>
            <label>Optional Email<br/>
                {{ reg_form.email }}</label><br/>
            <label>Password<br/>
                {{ reg_form.password1 }}</label><br/>
            <label>Repeat Password<br/>
                {{ reg_form.password2 }}</label><br/>
            <input type='submit' value='Register'/>
        </form>
    </div>
    
    <div class='box center'>
        <div class='box title'>Test Account</div>
        You can create a test account to try out the application without creating a login.<br/>
        <br/>
        Be aware that it will be deleted after a few days, but if you like the site, you can convert it into a full
        account by providing a username and password.<br/>
        <br/>
        <form method='POST' action='{% url "user:make_trial" %}'>
            {% csrf_token %}
            <input type='submit' value='Create Test Account'/>
        </form>
    </div>
{% endif %}
</section>

<div class='box underlink'>
    Please note, by using this site you agree to the use of cookies on your device. You can read about this in more
    detail in the <a href='{% url "privacy" %}'>Privacy Policy</a>.
</div>

{% endblock %}

users/templates/users/no_register.html
{% extends "base.html" %}

{% block title %}Sorry{% endblock %}

{% block content %}
<div class='box'>
    Sorry, you can't register due to site settings.
</div>
{% endblock %}

users/templates/users/password_changed.html
{% extends "base.html" %}

{% block title %}Password Changed{% endblock %}

{% block content %}
<div class='box'>
    <strong>Password Changed</strong><br/>
    <a href='/'>Return</a>
</div>
{% endblock %}

{% extends "base.html" %}

users/templates/users/preview.html
{% load static bookmark %}
<!DOCTYPE html>
<html>
    <head>
        <title>Theme Preview</title>
        <link rel='stylesheet' href='{% static "styles.css" %}'/>
        <link rel='stylesheet' href='{% static "theme_"|add:preview_theme|add:".css" %}'/>
        <style>
        .button {
            background-image:url('{% static "icons.png" %}');
        }
        
        :root {
            overflow:hidden;
            zoom:0.5;
        }
        </style>
        
        <script async src='//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'></script>
        <script async src='{% static "scripts.js" %}'></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </head>
    
    <body>
        <nav>
            {% if user.is_authenticated %}
                <a href='{% url "bookmarks:home" %}' {% if area == "bookmarks" %}class='active'{% endif %}>
                    Bookmarks
                </a>
                
                <a href='{% url "tags:home" %}' {% if area == "tags" %}class='active'{% endif %}>
                    Tags
                </a>
                
                <a href='{% url "search:home" %}' {% if area == "search" %}class='active'{% endif %}>
                    Search
                </a>
                
                {% if not user.settings.hide_settings %}
                    <a href='{% url "user:home" %}' {% if area == "user" %}class='active'{% endif %}>
                        Settings
                    </a>
                {% endif %}
                
                {% for t in pinned_tags %}
                <a href='{% url "tags:filter" tag=t.slug %}' {% if tag.pk == t.pk %}class='active'{% endif %}>
                    {{ t.name }}
                </a>
                {% endfor %}
            {% else %}
                <a href='{% url "user:login"%}' class='active'>
                    Log In
                </a>
            {% endif %}
        </nav>
        
        <main>
            <div id='bookmark-list'>
                {% for bm in bookmarks %}
                    {% bookmark bm %}
                {% empty %}
                    <div class='box'>
                        You have no bookmarks; how do you expect to pick a theme!?
                    </div>
                {% endfor %}
            </div>
        </main>
    </body>
</html>

users/templates/users/register.html
{% extends "base.html" %}

{% load form_errors %}

{% block title %}Register{% endblock %}

{% block content %}

{% form_errors form %}

<div class='box title'>
    {% if not upgrade %}Register New Account{% else %}Upgrade Trial Account{% endif %}
</div>

<div class='box center'>
    <form method='POST'>
        {% csrf_token %}
        <label>Username<br/>
            {{ form.username }}</label><br/>
        <label>Optional Email<br/>
            {{ form.email }}</label><br/>
        <label>Password<br/>
            {{ form.password1 }}</label><br/>
        <label>Repeat Password<br/>
            {{ form.password2 }}</label><br/>
        <input type='submit' value='Register'/>
    </form>
</div>

{% endblock %}

users/templates/users/reset.html
{% extends "base.html" %}
{% load form_errors %}

{% block title %}Reset Your Password{% endblock %}

{% block content %}

{% form_errors form %}

<div class='box'>
    <form method='POST'>
        {% csrf_token %}
        <strong>Forgot Password</strong><br/>
        Enter your email here to be sent a reset token<br/>
        {{ form.email }}<br/>
        <input type="submit" value="Reset Password" placeholder="email"/>
    </form>
</div>
{% endblock %}

users/templates/users/reset_complete.html
{% extends "base.html" %}

{% block title %}Password Reset Complete{% endblock %}

{% block content %}
<div class='box'>
    <strong>Password Reset Complete</strong><br/>
    <a href='{% url "user:login" %}'>Go to the log in page</a>
</div>
{% endblock %}

users/templates/users/reset_confirm.html
{% extends "base.html" %}
{% load form_errors %}

{% block title %}Password Reset{% endblock %}

{% block content %}

{% form_errors form %}

<div class='box'>
    {% if validlink %}
        Just enter a new password twice, and then you can log in.
        <form method="post">
            {% csrf_token %}
            <br/>{{ form.new_password1 }}
            <br/>{{ form.new_password2 }}
            <br/><input type="submit" value="Set Password" />
        </form>
    {% else %}
        That code is invalid; maybe it expired
    {% endif %}
</div>
{% endblock %}

users/templates/users/reset_done.html
{% extends "base.html" %}

{% block title %}Email Sent{% endblock %}

{% block content %}
<div class='box'>
    An email has been sent containing further information
</div>
{% endblock %}