autotags/urls.py
""" URLs for autotag related things

URLs are:
- home
- add
- delete
- (autotag)/html
- (autotag)/setPattern

"""

from django.urls import re_path
import autotags.views as views

app_name="autotags"
urlpatterns = [
    re_path(r'^$', views.home, name="home"),
    re_path(r'^add$', views.add, name="add"),
    re_path(r'^delete$', views.delete, name="delete"),
    re_path(r'^create$', views.create, name="create"),
    re_path(r'^check$', views.check, name="check"),
    
    re_path(r'^(?P<autotag>[0-9]+)/html$', views.html, name="html"),
    re_path(r'^(?P<autotag>[0-9]+)/setPattern$', views.setPattern, name="setPattern"),
]

bmat/urls.py
""" Root URL config """

from django.conf.urls import include
from django.urls import path, re_path
from django.contrib import admin

import bmat.views, bookmarks.urls, users.urls, tags.urls, search.urls, autotags.urls

admin.autodiscover()

urlpatterns = [
    re_path(r'^$', bmat.views.home, name="home"),
    re_path(r'^privacy$', bmat.views.privacy, name="privacy"),
    path(r"admin/", admin.site.urls),
    
    re_path(r'^user/', include("users.urls")),
    re_path(r'^bookmarks/', include("bookmarks.urls")),
    re_path(r'^autotags/', include("autotags.urls")),
    re_path(r'^tags/', include("tags.urls")),
    re_path(r'^search/', include("search.urls")),
]

autotags/models.py
""" Database models for bookmarks """

from django.contrib.auth.models import User
from django.db import models
from django.template import defaultfilters
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.utils.timezone import make_aware
from pytz import utc

from tags.models import Tag, Taggable
from tags import taggable
from bookmarks.templatetags.bookmark import bookmark
from users.models import Settings

import json

from datetime import datetime

_DT_FORMAT = "%a, %d %b %Y %H:%M:%S +0000"

@taggable("autotag")
class Autotag(Taggable):
    """ Automatic tag rule
    
    Contains:
    - owner:ForeignKey to User
    - pattern:CharField
    - tags:ManyToManyField to Tag
    - added:DateTimeField
    
    The owner of a rule is the user that added it.
    
    Simply put, if a bookmark is added, and the `pattern` of any Autotag owned by the same user matches it, then the
    tags of the autotag are added to the bookmark.
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    pattern = models.CharField(max_length=200)
    tags = models.ManyToManyField(Tag, related_name="autotags")
    added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ["-added"]
    
    def __str__(self):
        return ("Autotag '"+self.pattern+"' for "+self.owner.username).encode("ascii", "ignore").decode("ascii")
    
    def to_dir(self):
        """ Returns a dictionary representation of this autotag
        
        The keys of the object are the field names, and the values are the respective values.
        
        Tags are a list of dicts representing tags as per Tag.to_dir().
        """
        out = {}
        out["pattern"] = self.pattern
        out["id"] = self.pk
        out["added"] = self.added.astimezone(utc).strftime(_DT_FORMAT)
        out["tags"] = []
        
        for t in self.tags.all():
            out["tags"].append(t.to_dir())
        
        return out
    
    def to_json(self):
        """ Produces the JSON representation of this bookmark
        
        It's the JSON for the output of to_dir()
        """
        return json.dumps(self.to_dir())
    
    @staticmethod
    def from_json(jsonData, user):
        """ Given the JSON representation of the autotag, creates one for it
        
        Note that this SAVES the object to the database.
        
        If the "added" property of the object is absent, one will be created with the current date.
        """
        obj = json.loads(jsonData)
        
        at = Autotag(owner=user, pattern=obj["pattern"])
        
        at.save()
        
        if "added" in obj:
            at.added = make_aware(datetime.strptime(obj["added"], _DT_FORMAT), utc)
        
        for t in obj["tags"]:
            if isinstance(t, str):
                at.tag(t)
            else:
                at.tag(t["id"])
        
        at.save()
        
        return at
    
    @staticmethod
    def check_url(user, url):
        """ Loops through all the autotag instances owned by the user, and returns a list of tags that apply
        """
        #TODO: Should see if I should do this in the database
        url = url.lower()
        
        out = []
        
        for at in Autotag.by_user(user):
            if at.pattern.lower() in url:
                for t in at.tags.all():
                    out.append(t)
        
        return out
    
    @staticmethod
    def by_user(user):
        """ Get all the autotags owned by a given user """
        return Autotag.objects.all().filter(owner=user)

autotags/forms.py
""" Forms for manipulating tags """
from django import forms

from .models import Autotag

class AutotagSetPatternForm(forms.ModelForm):
    """ A model form for setting the pattern of an autotag rule
    
    It requires the fields "pattern".
    """
    class Meta:
        model = Autotag
        fields = ["pattern"]

autotags/views.py
""" View functions for autotags """

from django.contrib.auth.decorators import login_required
from django.core.exceptions import SuspiciousOperation, ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.validators import URLValidator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

from django.template import defaultfilters
from django.template.response import TemplateResponse
from django.views.decorators.http import require_POST

from tags.forms import AddTagForm, RemoveTagForm
from .forms import AutotagSetPatternForm
from .models import Autotag
from tags.models import Tag
from .templatetags.autotag import autotag as autotagTag
from users.models import Settings
from bmat.utils import make_page

import json

@login_required
def home(request):
    """ Home page is a list of all autotag rules and uses template index.html """
    ctx = {}
    
    # Set up the context
    ctx["area"] = "autotag"
    ctx["autotags"] = make_page(Autotag.by_user(request.user), request.GET.get("p"))
    
    return TemplateResponse(request, "autotags/index.html", ctx)


@login_required
@require_POST
def add(request):
    """ Adds a new autotag rule
    
    If it succeeds, it returns the JSON representation of the autotag it has added.
    
    If it fails it returns a JSON object with only an "error" property.
    """
    if "pattern" not in request.POST:
        raise SuspiciousOperation
    
    pattern = request.POST["pattern"]
    
    if not pattern:
        return HttpResponse('{"error":"Pattern must not be blank"}', content_type="application/json", status=422)
    
    at = Autotag(owner=request.user, pattern=pattern)
    
    at.save()
    
    if "tag" in request.POST:
        at.tag(request.POST["tag"])
    
    return HttpResponse(at.to_json(), content_type="application/json")


@login_required
@require_POST
def create(request):
    """ Given the json representation of an autotag, creates it
    
    The autotag must have been from "to_json", and must be the "obj" POST value.
    
    If it succeeds it returns a JSON object with "obj" being the JSON representation of the bookmark, "type" which
    is always "autotag" and "id" which is the id of the newly created autotag.
    """
    if "obj" not in request.POST:
        raise SuspiciousOperation
    
    try:
        at = Autotag.from_json(request.POST.get("obj"), request.user)
    except Exception:
        raise SuspiciousOperation
    
    out = {}
    out["type"] = "autotag"
    out["obj"] = at.to_json()
    out["id"] = at.pk
    
    return HttpResponse(json.dumps(out), content_type="application/json")


@login_required
@require_POST
def delete(request):
    """ Deletes the given autotag
    
    Accepts a singe POST parameter: `autotag`, which is the id of the rule to be deleted.
    
    This returns a JSON object with the following properties:
    deleted: The primary key of the deleted autotag, or null if it didn't exist.
    obj: The JSON representation of the deleted autotag, or null if it didn't exist.
    alreadyDeleted: True if and only if the autotag was deleted before this request.
    type: Always "autotag".
    
    If it encounters an error, the deleted property is null and alreadyDeleted is true
    """
    if "autotag" not in request.POST:
        raise SuspiciousOperation
    
    try:
        at = Autotag.objects.get(owner=request.user, pk=request.POST["autotag"])
    except Autotag.DoesNotExist:
        return HttpResponse(
            '{"obj":null, "type":"autotag", "deleted":null, "alreadyDeleted":true}', content_type="application/json"
        )
    
    id = at.pk
    json = at.to_json()
    at.delete()
    
    return HttpResponse(
        '{"deleted":'+str(id)+', "obj":'+json+', "type":"autotag", "alreadyDeleted":false}',
        content_type="application/json"
    )

@login_required
@require_POST
def check(request):
    """ Returns a JSON array of all the tags that match the url going by autotag settings
    
    Accepts a singe POST parameter: `url`, which is the url to check against
    
    This returns a JSON object with the following properties:
    results: An array of matching tags, as strings.
    
    If it encounters an error, an error property is set on the return object instead of results.
    """
    if "url" not in request.POST:
        raise SuspiciousOperation
    
    results = Autotag.check_url(request.user, request.POST["url"])
    
    results = map(lambda t: t.name, results)
    
    return HttpResponse(json.dumps({"results":results}), content_type="application/json")

@login_required
def html(request, autotag):
    """ Returns the autotag's HTML block (what it looks like on the page)
    
    This uses the templatetag autotagTag to render the provided bookmark.
    """
    at = get_object_or_404(Autotag, pk=autotag, owner=request.user)
    
    return TemplateResponse(
        request, "autotags/autotag.html", 
        autotagTag(at)
    )


@login_required
@require_POST
def setPattern(request, autotag):
    """ Sets the pattern of the given autotag
    
    Expects "pattern" to be provided in the post data.
    
    If it succeeds it returns a JSON object with "obj" being the JSON representation of the autotag, and "type" which
    is always "autotag".
    
    If it fails, it returns a JSON object with only an "error" proprerty.
    """
    atObj = get_object_or_404(Autotag, owner=request.user, pk=autotag)
    
    form = AutotagSetPatternForm(request.POST, instance=atObj)
    
    if not form.is_valid():
        e = list(form.errors.keys())[0]+": "+list(form.errors.values())[0][0]
        return HttpResponse('{"error":"'+e+'"}', content_type="application/json", status=422)
    
    form.save()
    
    return HttpResponse('{"obj":'+atObj.to_json()+', "type":"autotag"}', content_type="application/json")

autotags/templates/autotags/autotag.html
{% load tag %}
<div class='autotag box block {{ colour }}' data-id='{{ at.pk }}' data-taggable-type='autotag'>
    <div class='head'>
        <input type='checkbox' class='multiTagCheck{% if automulti %} multiTagCheckVisible{% endif %}'/>
        <div class='pattern noedit'><span class='nolink'>{{ at.pattern }}</span></div>
        <div class='pattern edit'>
            <form class='setPatternForm' method='POST' action='{% url "autotags:setPattern" autotag=at.id %}'>
                {% csrf_token %}
                <input class='setPatternEntry' name='pattern' type='text' value='{{ at.pattern }}'/>
            </form>
        </div>
        
        <div class='tags nomobile'>{% for t in tags %}{% tag t at %}{% endfor %}</div>
        
        <div class='buttons'>
            <a class='expand button' title='Show Options'>&nbsp;</a>
        </div>
    </div>
    <div class='head mobile'>
        <div class='tags'>{% for t in tags %}{% tag t at %}{% endfor %}</div>
    </div>
    
    <div class='body' style='display:none'>
        <div class='added nomobile'>&nbsp;</div>
        
        <div>
            {% addTag "autotag" at.pk %}
        </div>
        
        <div class='padLeft rightIfMobile buttons'>
            <a class='editPattern button noedit' title='Edit'>&nbsp;&nbsp;&nbsp;</a>
            <a class='setPattern button edit' style='display:none' title='Save'>&nbsp;</a>
            
            <form action='{% url "autotags:delete" %}' method='POST' class='deleteForm'
                data-undo-url='{% url "autotags:create" %}' data-undo-name='Autotag rule'
            >
                {% csrf_token %}
                <input type='hidden' name='autotag' value='{{ at.pk }}'/>
                <a class='delete button' title='Delete'>&nbsp;&nbsp;&nbsp;</a>
            </form>
        </div>
    </div>
    
    <div class='body' style='display:none'>
        <!-- Nothing here (yet?) -->
    </div>
</div>

autotags/templates/autotags/index.html
{% extends "base.html" %}
{% load autotag pages pattern_add tag %}

{% block title %}Automatic Tag Rules{% endblock %}

{% block content %}
<div class='box flex'>
    {% multiTagButton %}{% url_add %}
</div>

{% multiTag "autotag" %}

<div class='box'>
    How this works is simple:
    <ul>
        <li>Enter a pattern in the box above, and click add &quot;Add Pattern&quot;</li>
        <li>Add some tags to the pattern by clicking the menu button and adding it there</li>
        <li>Now, whenever you add a bookmark whose URL contains the pattern, it will be tagged with those tags</li>
    </ul>
</div>

<div id='autotag-list'>
    {% for at in autotags %}
        {% autotag at %}
    {% empty %}
        <div class='box'>
            You have no rules yet.
        </div>
    {% endfor %}
</div>
{% pages autotags "autotags:home" %}
{% endblock %}

autotags/templates/autotags/pattern_add.html
<form id='add-pattern' method="POST" style='display:flex'>
    {% csrf_token %}
    <input type='text' name='pattern' style='width:100%' placeholder='Add new pattern'/>
    <input type='submit' value='Add'/>
</form>